### ISSUE TITLE
Running problem with SVM & KNN

### ISSUE THREAD

**Issue by taha7ussein007** [FantacherJOY/Arabic-text-classification#1]
while i'm trying to run SVM model i got this error 
TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.
coming from this line 
X_train_res, y_train_res = sm.fit_sample(X_train_tfidf, y_train)
----------------------------------------------------------------------------
Also when i tried to run KNN i got this error 
ValueError: kd_tree does not work with sparse matrices. Densify the data, or set algorithm='brute'
---------------
Notice : my dataset is a little bit large it is about 25 k (rows)  * 2  (columns)
thanks in advance

**Comment by FantacherJOY** [comment]
Sorry, it's because of the data. I uploaded the 6000 data file. I think it will work now.
